---
title: "heatmap"
author: "longlong"
date: "2022/2/4"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message  = F) 
```

```{r}
rm(list = ls())  ## 魔幻操作，一键清空~
options(stringsAsFactors = F) 

load("input.Rdata")
load("input_rpkm.Rdata")

library(pheatmap)

dat1=dat[!(grepl("ERCC",rownames(dat))),]
```
## get sd top 100 gene
```{R}
apply(dat1, 1, sd)
dat2=dat1[names(tail(sort(apply(dat1, 1, sd)),100)),]


#draw heatmap
pheatmap(dat2)

#hcluster
clus1=hclust(dist(t(dat2)))
plot(clus1)
k=cutree(clus1,4)
pd=data.frame(group=k)
rownames(pd)=names(k)
#draw heatmap
pheatmap(dat2,annotation_col =pd)


#scale dat
dat3=  scale(t(dat2))
dat3[dat3>2]=2
dat3[dat3< -2]=-2
hist(dat3)

#group
clus2=hclust(dist(dat3))
plot(clus2)
k1=cutree(clus2,4)
pd1=data.frame(group=k1)
rownames(pd1)=names(k1)

#heatmap
pheatmap(t(dat3),annotation_col=pd1)
```

