---
title: "scran"
author: "WCL"
date: '2022-09-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

读取数据
---
```{r}
suppressMessages(library(scRNAseq))
suppressMessages(library(scuttle))
suppressMessages(library(scran))
sce <-suppressMessages(GrunPancreasData())
```

质控，处理掉质量差的细胞
-----
计算ERCC，可以通过subset确定不同的种群
```{r}
qcstats <- perCellQCMetrics(sce)
```


计算低质量细胞
```{r}
qcfilter <- quickPerCellQC(qcstats, percent_subsets="altexps_ERCC_percent")
sce <- sce[,!qcfilter$discard]
summary(qcfilter$discard)
```

log-norm处理
```{r}
# 表达相似的细胞聚类
clusters <- quickCluster(sce)
# scale data
sce <- computeSumFactors(sce, clusters=clusters)
summary(sizeFactors(sce))
# 基于scale factor做lognorm
sce <- logNormCounts(sce)
```


查看基因的变异情况，并取高变异基因
----
mean：基因平均表达；total：基因方差
tech：技术变异（拟合值），bio：生物学变异（残差值）
```{r}
dec <- modelGeneVar(sce)
plot(dec$mean, dec$total, xlab="Mean log-expression", ylab="Variance")
# 画拟合曲线
curve(metadata(dec)$trend(x), col="blue", add=TRUE)
```

如果有ERCC（spike-in）用下面的代码
```{r}
dec2 <- modelGeneVarWithSpikes(sce, 'ERCC')
plot(dec2$mean, dec2$total, xlab="Mean log-expression", ylab="Variance")
points(metadata(dec2)$mean, metadata(dec2)$var, col="red")
curve(metadata(dec2)$trend(x), col="blue", add=TRUE)
```


如果有不同的分类条件，可以单独拟合
density.weights：关闭权重的影响
```{r}
dec3 <- modelGeneVar(sce, block=sce$donor, density.weights=FALSE)
per.block <- dec3$per.block
par(mfrow=c(3, 2))
for (i in seq_along(per.block)) {
  decX <- per.block[[i]]
  plot(decX$mean, decX$total, xlab="Mean log-expression", 
       ylab="Variance", main=names(per.block)[i])
  curve(metadata(decX)$trend(x), col="blue", add=TRUE)}
```

提取基因
```{r}
# Get the top 10% of genes.
top.hvgs <- getTopHVGs(dec, prop=0.1)
# Get the top 2000 genes.
top.hvgs2 <- getTopHVGs(dec, n=2000)
# Get all genes with positive biological components.
top.hvgs3 <- getTopHVGs(dec, var.threshold=0)
# Get all genes with FDR below 5%.
top.hvgs4 <- getTopHVGs(dec, fdr.threshold=0.05)
```



用subset.row来选择高变异基因进行下游处理
```{r}
sce <- fixedPCA(sce, subset.row=top.hvgs)
reducedDimNames(sce)
```

PCA dim数量自动选择
-----
method1：用技术变异来衡量，要求技术变异大于总体变异，排除生物学变异为负数的基因。
```{r}
sced <- denoisePCA(sce, dec2, subset.row=getTopHVGs(dec2, prop=0.1))
ncol(reducedDim(sced, "PCA"))
```

method2：dim不少于cluster的数量
```{r}
output <- getClusteredPCs(reducedDim(sce))
npcs <- metadata(output)$chosen
reducedDim(sce, "PCAsub") <- reducedDim(sce, "PCA")[,1:npcs,drop=FALSE]
npcs
```




后面出图可以用seurat，也可以再继续学习
- https://bioconductor.org/packages/3.15/bioc/vignettes/scran/inst/doc/scran.html
